### ISSUE TITLE
Failed to login kindle account due to Amazon account verification

### ISSUE THREAD

**Issue by AndyJZhao** [lg08/kindle_notion_syncer#2]
Hi, thanks for the great work (and also the detailed step-by-step Readme)!
For me, the app wasn't working as everytime the app tries to sign-in, it got stuck at the Amazon account email verification step shown below:
![image](https://user-images.githubusercontent.com/26394168/183523627-bee4edc3-c12f-4764-aa8a-d4bb0eaa6deb.png)
Is there any workarounds?
Thanks again for your great work!

**Comment by lg08** [comment]
Yes! Just hit approve one time and it should go away from then on!
